# Generated by Django 3.1.6 on 2021-02-16 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_standard'),
    ]

    operations = [
        migrations.CreateModel(
            name='WidaEvaluation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(editable=False)),
                ('updated_at', models.DateTimeField()),
                ('url "', models.IntegerField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.student')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
