# Generated by Django 3.1.7 on 2021-03-12 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_auto_20210227_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='semester',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8')], default='1', max_length=20),
        ),
        migrations.AlterField(
            model_name='standard',
            name='statement_name',
            field=models.CharField(max_length=200),
        ),
    ]
