name: Release Project Container
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
jobs:
  release-server:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build Backtrack's Docker image
      run: docker build . --file Dockerfile --tag backtrack-server:latest
    - name: Publish Backtrack Server to Registry
      uses: elgohr/Publish-Docker-Github-Action@v5
      with:
        name: registry.digitalocean.com/parrotmac/backtrack-server:latest
        username: ${{ secrets.DO_REGISTRY_TOKEN }}
        password: ${{ secrets.DO_REGISTRY_TOKEN }}
        registry: registry.digitalocean.com
        context: .
        dockerfile: Dockerfile
        buildoptions: "--label git_sha=${GITHUB_SHA}"
